volumes:
  pulsar-zookeeper:
    driver: ${VOLUMES_DRIVER}

services:

### PULSAR ZOOKEEPER ##############################################
  pulsar-zookeeper:
    build:
      context: ${PULSAR_ZOOKEEPER_HOST_PATH}
      args:
        PULSAR_VERSION: ${PULSAR_VERSION}
    container_name: ${PULSAR_ZOOKEEPER_CONTAINER_NAME}
    hostname: ${PULSAR_ZOOKEEPER_HOSTNAME}
    user: root
    privileged: true
    command: >
      bash -c "bin/apply-config-from-env.py conf/zookeeper.conf && \
              bin/generate-zookeeper-config.sh conf/zookeeper.conf && \
              exec bin/pulsar zookeeper"
    volumes:
      - "${DATA_PATH_HOST}/${PULSAR_ZOOKEEPER_CONTAINER_NAME}:/pulsar/data/zookeeper"
    environment:
      - "TZ=${TZ}"
      - "metadataStoreUrl=zk:${PULSAR_ZOOKEEPER_CONTAINER_NAME}:2181"
      - "PULSAR_MEM=-Xms256m -Xmx256m -XX:MaxDirectMemorySize=256m"
    networks:
      backend:
        ipv4_address: ${PULSAR_ZOOKEEPER_BACKEND_IP}
    healthcheck:
      test: ["CMD", "bin/pulsar-zookeeper-ruok.sh"]
      interval: 10s
      timeout: 5s
      retries: 30